CREATE DATABASE DS_MERCADO;

USE DS_MERCADO;


CREATE TABLE USUARIO(
ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
NOME_USUARIO VARCHAR(50),
SENHA_USUARIO VARCHAR(50)
);

CREATE TABLE ESTOQUE(
ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
);